### PR TITLE
Fix email regexp

### LINKED ISSUE #69: existing email validation in ckan is not complete
CKAN existing email validation seems to not be complete, and needs fixing of the regexp used.

### PR DESCRIPTION
**Pull request by sivang**
- Fixes #69 
- Contributed upstream: https://github.com/ckan/ckan/pull/4720

### CODE REVIEW

**Comment by sivang** [comment]
> This looks good but some tests would be great

Where do you add tests on a plugin ?

**Comment by zelima** [comment]
@sivang we need a test for validator, not plugin https://github.com/CivicActions/ckanext-ed/tree/master/ckanext/ed/tests

**Comment by zelima** [comment]
@sivang I assume we can close this in favor of https://github.com/CivicActions/docker-ckan-ed/pull/2. Please close if so

**Comment by sivang** [comment]
yes.

**Comment by zelima** [comment]
FIXED in https://github.com/CivicActions/docker-ckan-ed/pull/2

**Pull request closed without merging**
